export class ApiData {
    constructor(
        private state?: string,
        private positive?: number,
        private positiveScore?: number,
        private negativeScore?: number,
        private negativeRegularScore?: number,
        private commercialScore?: number,
        private grade?: string,
        private score?: number,
        private notes?: string,
        private dataQualityGrade?: string,
        private negative?: number,
        private pending?: any,
        private hospitalizedCurrently?: number,
        private hospitalizedCumulative?: any,
        private inIcuCurrently?: any,
        private inIcuCumulative?: any,
        private onVentilatorCurrently?: any,
        private onVentilatorCumulative?: any,
        private recovered?: number,
        private lastUpdateEt?: string,
        private checkTimeEt?: string,
        private death?: number,
        private hospitalized?: any,
        private total?: number,
        private totalTestResults?: number,
        private posNeg?: number,
        private fips?: string,
        private dateModified?: string,
        private dateChecked?: string,
        private hash?: string,
    ) { }
}
